POST http://localhost:3000/api/athletic
Content-Type: application/json
{
    "name": "CRYPTO",
    "description": "Atlética de TI da Unisul",
}

###
GET http://localhost:3000/api/athletic/1
Content-Type: application/json

###
GET http://localhost:3000/api/athletic
Content-Type: application/json

###
PATCH http://localhost:3000/api/athletic/5
Content-Type: application/json
{
    "name": "CRYPTO",
    "description": "Atlética de TI da Unisul",
    "points": 0,
    "gameId": 2
}

###
DELETE http://localhost:3000/api/athletic/1
Content-Type: application/json